config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :skills do
    collection do
      get :search
    end
    resources :skills, only: [:create, :show, :edit, :update, :destroy]
  end

  resources :users do
    resources :reviews, only: [:create, :show, :edit, :update, :destroy]
    resources :reservations
    resources :messages, only: [:index,:show, :new, :create, :destroy]
  end

  post 'validate', to: 'reservations#validate'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :skills
  has_many :reservations_as_teacher, class_name: 'Reservation', foreign_key: 'teacher_id', dependent: :destroy
  has_many :reservations_as_student, class_name: 'Reservation', foreign_key: 'student_id', dependent: :destroy
  has_many :sent_messages, foreign_key: 'student_id', class_name: 'Message'
  has_many :received_messages, foreign_key: 'teacher_id', class_name: 'Message'
  has_many :reviews, dependent: :destroy



  def self.teachers
    where(role: 'teach')
  end
  def self.students
    where(role: 'learn')
  end



  # def validated_reservations_count
  #   reservations.where(statut: 'Validée').count
  # end


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :photo

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    params.require(:user).permit(:name, :last_name, :address, :email, :skills, :interest, :role, :rating)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #  skip_before_action :authenticate_user!, only: :index
 before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :authentification
  def index

   @users = User.all
   @markers = @users.geocoded.map do |user|
    {
      lat: user.latitude,
      lng: user.longitude
    }
  end

   @teachers = @users.where(role: "teach")

   @students = @users.where(role: "learn")
   # @users.select {|user| user.role == 'teach'}
   # raise

  end

  def new
    @user = User.new

  end
  def create
    @user = User.new(user_params)

    if @user.save
      if @user == 'learn' # Ajout de la condition ici pour vérifier si l'utilisateur est un étudiant
        @review = Review.new(user: @user, teacher: some_teacher_instance, content: params[:review][:content], rating: params[:review][:rating])
        @review.save
      elsif @user == 'teach' # Ajout de la condition ici pour vérifier si l'utilisateur est un enseignant
        @skill = Skill.new(user: @user, title: params[:skills])
      end

      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
   @review = Review.new
   @user = User.find(params[:id])
   @users = User.all
   @reservation = Reservation.new
   @reviews = Review.where(teacher_id: @user.id)
   @markers = @users.geocoded.map do |user|
      if user == @user
        {
          lat: user.latitude,
          lng: user.longitude
        }
      end
    end
  end


  def edit
  end

  def  update
   if @user.update(user_params)
     redirect_to user_path(@user), notice: 'User was successfully updated.'
   else
     render :edit, status: :unprocessable_entity
   end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end



  private


  def user_params
    params.require(:user).permit(:name, :last_name, :address, :email, :skills, :interest, :teacher, :rating, :photo)
  end

   def set_user
    @user = User.find(params[:id])
   end
 end

app/views/users/edit.html.erb
<%= simple_form_for @user, url: user_path(@user), method: :patch do |f| %>
  <div class="container mt-4">
    <h1 class="text-center">Update Your Profile <%= @user.name %></h1>

    <div class="#">
      <div class="card-body">
          <%= f.input :photo, as: :file %>

        <%= f.input :name, label: "Name", input_html: { class: "form-control" } %>

        <%= f.input :last_name, label: "Last Name", input_html: { class: "form-control" } %>

        <%= f.input :interest, label: "Interest", input_html: { class: "form-control" } %>

        <%= f.input :email, label: "Email", input_html: { class: "form-control" } %>

        <%= f.input :address, label: "Address", input_html: { class: "form-control" } %>


        <div class="text-center mt-3">
          <%= f.button :submit, "Update", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<%= render "shared/section" %>
<div class="container gap-3 d-flex flex-column mt-4">
<%= render "shared/category" %>
<% if current_user.role == 'learn' %>
  <h3 class="text-center my-4">Nos Meilleurs Formateurs</h3>
  <div class="row">
    <% @teachers.each do |t| %>
  <div class="col-md-3 mb-4">
     <%= link_to user_path(t), class:"card_formateur" do %>

<<<<<<< HEAD
      <% if t.photo.attached? %>
        <div class="image">
          <%= cl_image_tag(t.photo.key, height: 500, width: 500, crop: :fill) %>
        </div>
      <% end %>
      <div class="info">
        <div>
          <p class="name"><%= t.name %> <%= t.last_name %></p>
          <p class="function"><i class="fas fa-book"></i> <%= t.interest %></p>
        </div>
        <div class="stats">
          <p class="flex" id="avis">
            Avis
            <span class="state-value"><%= render_rating(t.rating) %></span>
          </p>
=======
<div class="container">
  <div class="col-12"><br>
    <div class="row">
      <% @teachers.each do |t| %>
      <!--====== CARD FORMATEUR PART START ======-->
        <div class="col-md-3">
          <div class="cardm">
            <div class="flat-card d-flex">
              <div class="flat-card-content d-flex flex-column">
                <div class="flat-card-title">
                  <div class="cardimg">

                    <img src="https://res.cloudinary.com/deydjvnm9/image/upload/v1700222106/qtazyi2l8ymjlfcnybhv.jpg"
                      class="img-thumbnail" alt="exmpl" width="300" height="250">
                  </div>
                  <div class="cardm">
                  <h5>
                    <%= t.name %>
                  </h5>
                  <h5>
                    <%= t.last_name %>
                  </h5>
                  <p>
                    <%= t.email %>
                  </p>
                  <p>
                    <%= t.address %>
                  </p>
                  <p>
                    <%= t.interest %>
                  </p>
                  <%= link_to "View More details", user_path(t)  %>
                </div>
              </div>
              </div>

            </div>
          </div>

>>>>>>> 4ed8291516d5e783919b44db0b354776e73e887f
        </div>

      </div>

   <% end %>
  </div>
<% end %>

</div>
<% end %>
  </div>

app/views/users/new.html.erb
<%= simple_form_for @user do |f| %>
  <div class="container mt-4">
    <h1 class="text-center">Nouveau Formateur</h1>

    <div class="card mt-4">
      <div class="card-body">
        <%= f.input :name, label: "Name", input_html: { class: "form-control" } %>

        <%= f.input :last_name, label: "Last Name", input_html: { class: "form-control" } %>

        <%= f.input :interest, label: "Interest", input_html: { class: "form-control" } %>

        <%= f.input :email, label: "Email", input_html: { class: "form-control" } %>

        <%= f.input :address, label: "Address", input_html: { class: "form-control" } %>

        <!-- Ajoutez d'autres champs du formulaire en fonction de vos besoins -->

        <div class="text-center mt-3">
          <%= f.button :submit, "Create Formateur", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<!-- app/views/offers/show.html.erb -->  <% content_for :meta_title, "#{@user.name} is on #{DEFAULT_META["meta_product_name"]}" %>  <% content_for :meta_description, @user.skills %>  <% content_for :meta_image, cl_image_path(@user.photo.key) %>
<div class="teacher-profile">

  <!-- Header Section with Avatar and Name -->
  <div class="teacher-header">
    <div class="teacher-avatar">
      <%= cl_image_tag @user.photo.key, height: 400, width: 400, crop: :fill, class: "avatar-img" if @user.photo.attached? %>
    </div>
    <div class="teacher-info">
      <h4>Bonjour, je suis</h4>
      <h1><%= @user.name %></h1>
    </div>
  </div>

  <!-- Skills and Interests Section -->
<% if @user.role == 'teach' %>
  <div class="teacher-details">
    <h2><i class="fas fa-cog"></i>Compétences</h2>
    <ul>
      <% @user.skills.each do |skill| %>
        <li class="skill">
          <strong><%= skill.title %>:</strong> <%= skill.description %>
        </li>
      <% end %>
    </ul>
    <p class="interests"><strong>Intérêts :</strong> <%= @user.interest %></p>
  </div>
<% end %>

<% if @user.role == 'learn' %>
  <div class="teacher-details">
    <h2><i class="fas fa-cog"></i>Intérets</h2>

    <p class="interests"><strong>Compétences :</strong> <%= @user.interest %></p>
  </div>
<% end %>


  <!-- Action Button for Teachers -->
  <% if current_user == @user && @user.role == "teach" %>
    <div class="teacher-actions">
      <%= link_to "Ajouter une compétence", new_skill_path, class: "btn btn-primary" %>
    </div>
  <% end %>

  <!-- Booking Section for Students -->
  <div class="about-content" data-controller="toggle">
    <% if @user.role == 'teach' && @user != current_user %>
      <button class="toggle-btn" data-action="click->toggle#fire"><i class='fas fa-calendar-alt'></i>  Réserver cette formation</button>
      <div data-toggle-target="display" class="reservation-form d-none">
        <%= simple_form_for([@user, @reservation]) do |f| %>
          <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker" }, placeholder: 'JJ/MM/AAAA' }, label: 'Date de début', label_html: { class: 'form-label' } %>
          <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker" }, placeholder: 'JJ/MM/AAAA' }, label: 'Date de fin', label_html: { class: 'form-label' } %>

          <%= f.submit "Réserver maintenant", class: "btn btn-info" %>
        <% end %>
      </div>
    <% end %>

  </div>

    <div class="map-container" data-controller="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" data-map-markers-value="<%= @markers.to_json %>"></div>

<%if @user.role ==  "teach"  %>
    <div class="reviews" data-controller="reviews">

        <div class="title-review">

          <h3>Avis des étudiants</h3>
          <% if @reviews.size > 1 %>
          <button data-action="click->reviews#toggleReviews" data-reviews-target="toggleButton" class="btn btn-info mt-2">Voir plus</button>
        <% end %>
        </div>
      <div id="reviews-container">
        <% displayed_reviews = @reviews.take(1) %>
        <% additional_reviews = @reviews.drop(1) %>

        <% displayed_reviews.each do |review| %>
          <div class="review">
            <p><span class="star-rating"><%= render_rating(review.rating) %></span> <br><%= review.content %></p>
          </div>
        <% end %>

        <% if additional_reviews.any? %>
          <div class="additional-reviews d-none" data-reviews-target="additionalReviews" >
            <% additional_reviews.each do |review| %>
              <div class="review">
                <p><span class="star-rating"><%= render_rating(review.rating) %></span> <br><%= review.content %></p>

              </div>
            <% end %>
          </div>

        <% end %>
      </div>

<%if current_user.role == "learn"  %>
      <%= form_with(model: [@user, Review.new], url: user_reviews_path(@user), local: true) do |form| %>
  <div class="form-group">
    <%= form.label :rating, 'Votre note:' %>
    <%= form.number_field :rating, class: 'form-control', placeholder: 'Entrez votre note', min:0, max: 5 %>
  </div>

        <div class="form-group">
          <%= form.label :content, 'Votre commentaire:' %>
          <%= form.text_area :content, class: 'form-control', placeholder: 'Partagez votre expérience...' %>
        </div>

        <%= form.submit 'Envoyer la critique', class: 'btn btn-primary' %>
      <% end %>


    </div>
<% end %>
<% end %>


  <!-- Footer Actions -->
  <div class="footer-actions">
    <%= link_to "Retour à l'accueil", root_path, class: "btn btn-secondary" %>
    <%= link_to "Modifier le profil", edit_user_path(current_user), class: "btn btn-warning" if current_user == @user %>
  </div>
</div>