config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :skills do
    collection do
      get :search
    end
    resources :skills, only: [:create, :show, :edit, :update, :destroy]
  end

  resources :users do
    resources :reviews, only: [:create, :show, :edit, :update, :destroy]
    resources :reservations
    resources :messages, only: [:index,:show, :new, :create, :destroy]
  end

  post 'validate', to: 'reservations#validate'

end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  #  skip_before_action :authenticate_skill!, only: :index
 before_action :set_skill, only: [:show, :edit, :update, :destroy]
  # before_action :authentification
  def index
    if params[:query].present?
      @skills = Skill.where(title: params[:query])
    else
      @skills = Skill.all
    end
  end

  def new
    @skill = Skill.new
  end

  def create
   @skill = Skill.new(skill_params)
   @skill.user = current_user
   if @skill.save
     redirect_to skill_path(@skill), notice: 'skill was successfully created.'
   else
     render :new, status: :unprocessable_entity
   end
 end

  def show
   #raise
  end

  def edit

  end

  def search
    @skills = if params[:query].present?
               perform_search(params[:query])
             else
               Skill.all
             end
    render :index
  end

  def perform_search(query)
    Skill.where("lower(title) ILIKE ?", "%#{query.downcase}%")
  end

  def  update
   if @skill.update(skill_params)
     redirect_to skill_path(@skill), notice: 'skill was successfully updated.'
   else
     render :edit, status: :unprocessable_entity
   end
  end

  def destroy
    @skill.destroy
    redirect_to skills_path
  end


  private



  def skill_params
   params.require(:skill).permit(:title, :description)
 end

  def set_skill
   @skill = Skill.find(params[:id])
 end
 end

app/views/skills/edit.html.erb
<div class="bg">
<%= simple_form_for @skill, url: skill_path(@skill), method: :patch do |f| %>
  <div class="container mt-4">
    <h1 class="text-center" style="color: aliceblue;">Modifier Mes Compétences en <%= @skill.title %></h1>

    <div class="cardm mt-4">
      <div class="card-body" style="color: aliceblue;">
        <%= f.input :title, label: "Titre", input_html: { class: "form-control" } %>

        <%= f.input :description, label: "Description", input_html: { class: "form-control" } %>



        <div class="text-center mt-3" style="color: aliceblue;">
          <%= f.button :submit, "Mise à jour", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/skills/index.html.erb
<div class="container my-4">
<div class="text-start mb-3">
  <% if @skills.count.zero? %>
    <p class="text-muted">Aucun résultat trouvé pour la requête "<%= params[:query] %>"</p>
  <% else %>
    <p>Il y a <span class="fw-bold"><%= @skills.count %></span> résultats pour la recherche<em class="font-italic">"<%= params[:query] %>"</em> :</p>
  <% end %>
</div>

  <div class="row">
    <% @skills.each do |skill| %>
      <div class="col-md-4 mb-4">
        <div class="custom-card">
          <!-- User profile image -->
          <div class="custom-card-img-top">
            <%= cl_image_tag(skill.user.photo.key, height: 300, width: 300, crop: :fill) if skill.user.photo.attached? %>
          </div>

          <div class="custom-card-body">
            <h5 class="custom-card-title text-center"><%= skill.title %></h5>
            <p class="custom-card-text">

              <%=  skill.description %>
            </p>
            <div class="text-center mt-3">
              <!-- Add an icon here if desired -->
              <a href="<%= user_path(skill.user) %>" class="custom-btn custom-btn-success">Voir le Profil</a>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="text-center mt-2"> <!-- Ajout de la classe "text-center" pour centrer le bouton -->
    <%= link_to "Retour", root_path , class: "custom-btn custom-btn-secondary" %>
  </div>
</div>

app/views/skills/new.html.erb
<div class="bg">
  


    <%= simple_form_for @skill do |f| %>
      <div class="container mt-4">
        <h1 class="text-center" style="color: aliceblue;">Nouvelle compétence</h1>

        <div class="cardm mt-4" style="color: aliceblue;">
          <div class="card-body">
            <strong></strong><%= f.input :title, label: "Title:" , input_html: { class: "form-control" } %></strong>

              <strong><%= f.input :description, label: "Description:" , input_html: { class: "form-control" } %></strong>


                <div class="text-center mt-3">
                  <%= f.button :submit, "Rajouter une compétence" , class: "btn btn-primary" %>
                </div>
          </div>
        </div>
      </div>
      <% end %>
 
</div>

app/views/skills/search.html.erb
<!-- app/views/boats/search.html.erb -->
<div class="container mt-3">
  <div class="row">
    <div class="col-12"><br>
      <h5>Quelle nouvelle compéténce voulez-vous apprendre ?</h5>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% if @query %>
        <p>You searched for <strong><%= @query %></strong>. We found <%= @skills.count %> Skills out of our <%= Skill.count %> on our website.</p>
      <% else %>
        <p>All <%= Skill.count %> skills.</p>
      <% end %>


    </div>
  </div><br>
</div>

app/views/skills/show.html.erb
<div class="bg">
<div class="container mt-5">
  <h1 class="text-center" style="color: aliceblue;">Mes Compétences <%= @skill.title %></h1>

  <div class="cardm mt-4" >
    <div class="card-body">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><strong>Title:</strong> <%= @skill.title %></li>
        <li class="list-group-item"><strong>Description:</strong> <%= @skill.description %></li>
      </ul>

      <div class="d-flex justify-content-center mt-3">
        <%= link_to "Edit skill", edit_skill_path(@skill), class: "btn btn-primary mx-2" %>
        <%= link_to "Come Back", skills_path, class: "btn btn-secondary mx-2" %>
         <%= link_to "delete",  skill_path(@skill), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>
</div>