config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :skills do
    collection do
      get :search
    end
    resources :skills, only: [:create, :show, :edit, :update, :destroy]
  end

  resources :users do
    resources :reviews, only: [:create, :show, :edit, :update, :destroy]
    resources :reservations
    resources :messages, only: [:index,:show, :new, :create, :destroy]
  end

  post 'validate', to: 'reservations#validate'

end

app/views/shared/_category.html.erb
  <h3 class="text-center my-4">Top catégories</h3>
  <div class="d-flex flex-wrap flex-row gap-5">
    <%= link_to search_skills_path(:query => "Developpement") do %>
      <div class="card">
        <div class="face back">
          <div class="content">
            <span class="stars"></span>
            <p class="desc">
              Créer des mondes numériques d'un simple clic.
            </p>
          </div>
        </div>
        <div class="face front" style="background-image: url('<%= asset_path 'developpement.jpeg' %>'); background-size: cover; background-position: center; background-repeat: no-repeat; border-radius: 15px; transition: 0.5s;">
          <b class="small-text">Dev</b>
        </div>
      </div>
    <% end %>

    <%= link_to skills_path(:query => "danse") do %>
      <div class="card">
        <div class="face back">
          <div class="content">
            <span class="stars"></span>
            <p class="desc">
              Le langage du corps, expression infinie de l'émotion.
            </p>
          </div>
        </div>
        <div class="face front" style="background-image: url('<%= asset_path 'danse.jpeg' %>'); background-size: cover; background-position: center; background-repeat: no-repeat; border-radius: 15px; transition: 0.5s;">
          <b class="small-text">Danse</b>
        </div>
      </div>
    <% end %>

    <%= link_to skills_path(:query => "design") do %>
      <div class="card">
        <div class="face back">
          <div class="content">
            <span class="stars"></span>

            <p class="desc">
              L'élégance au service de l'innovation.
            </p>
          </div>
        </div>
        <div class="face front" style="background-image: url('<%= asset_path 'design.jpeg' %>'); background-size: cover; background-position: center; background-repeat: no-repeat; border-radius: 15px; transition: 0.5s;">
          <b class="small-text">Design</b>
        </div>
      </div>
    <% end %>

    <%= link_to skills_path(:query => "cuisine") do %>
      <div class="card">
        <div class="face back">
          <div class="content">
            <span class="stars"></span>
            <p class="desc">
              L'art de créer des moments délicieux et inoubliables.
            </p>
          </div>
        </div>
        <div class="face front" style="background-image: url('<%= asset_path 'cuisine.jpeg' %>'); background-size: cover; background-position: center; background-repeat: no-repeat; border-radius: 15px; transition: 0.5s;">
          <b class="small-text">Cuisine</b>
        </div>
      </div>
    <% end %>

    <%= link_to skills_path(:query => "mathématiques") do %>
      <div class="card">
        <div class="face back">
          <div class="content">
            <span class="stars"></span>
            <p class="desc">
              La clé de l'univers quantifiable.
            </p>
          </div>
        </div>
        <div class="face front" style="background-image: url('<%= asset_path 'mathématiques.jpeg' %>'); background-size: cover; background-position: center; background-repeat: no-repeat; border-radius: 15px; transition: 0.5s;">
          <b class="small-text">Maths</b>
        </div>
      </div>
    <% end %>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="footer-area pt-5 pb-3">
    <div class="container">
<<<<<<< HEAD
        <div class="row">
            <div class="col-md-3">
                <%= image_tag("uskillslogo.png", alt: "App Logo", class: "footer-logo") %>
                <p class="mt-3">About us.</p>
            </div>
            <div class="col-md-2">
                <h5>Quick Links</h5>
                <ul class="footer-links">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Courses</a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <h5>Our Courses</h5>
                <ul class="footer-links">
                    <li><a href="#">Design</a></li>
                    <li><a href="#">Development</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <h5>Contact Us</h5>
                <ul class="footer-contact">
                    <li>Phone: +33 6 69 88 57 80</li>
                    <li>Email: USkills@gmail.com</li>
                    <li>Address: Random Road Paris, France</li>
                </ul>
            </div>
            <div class="col-md-2">
                <h5>Follow Us</h5>
                <ul class="list-inline social-icons">
                <br>
                    <li class="list-inline-item"><a href="https://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook-f"></i></a></li>
                    <li class="list-inline-item"><a href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
                    <li class="list-inline-item"><a href="https://www.twitter.com/" target="_blank"><i class="fa-brands fa-twitter"></i></a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <!-- Nouvelle liste pour les logos -->
                <ul class="list-inline social-icons">
                    <li class="list-inline-item"><a href="#"><i class="lni lni-linkedin-original"></i></a></li>
                </ul>
=======
        <section>
            <div class="row">
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <!-- <div class="footer-widget"> -->
                    <%= image_tag("uskillslogo.png", alt: "App Logo" , class: "img-thumbnail" , size: "90x90" ) %>
                        <p>About us .</p>
                        <!-- </div> -->
                </div>
                <div class="col-xl-2 col-lg-2 offset-xl-1 offset-lg-1 col-md-6">
                    <!-- <div class="footer-widget"> -->
                    <h5>Quick Links</h5>
                    <ul>
                        <li><a href="javascript:void(0)">Home</a></li>
                        <li><a href="javascript:void(0)">Courses</a></li>
                       
                    </ul>
                    <!-- </div> -->
                </div>
                <div class="col-xl-2 col-lg-2 col-md-6">
                    <!-- <div class="footer-widget"> -->
                    <h5>Our Course</h5>
                    <ul>
                        <li><a href="javascript:void(0)">Design</a></li>
                        <li><a href="javascript:void(0)">Development</a></li>
                        
                    </ul>
                    <!-- </div> -->
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <!-- <div class="footer-widget"> -->
                    <h5>Contact Us</h5>
                    <ul>
                        <li>
                            <p>Phone: +336-9273-3867</p>
                        </li>
                        <li>
                            <p>Email: USkills@gmail.com</p>
                        </li>
                        <li>
                            <p>Address: Random Road Paris<br> France</p>
                        </li>
                    </ul>
                    <!-- </div> -->
                </div>
            </div>
            <div class="footer-credit">
                <div class="row">
                    <div class="col-md-6">
                        <div class="copy-right text-center text-md-left">
                            <p>Designed and Developed by <a href="https://uideck.com" rel="nofollow">USkills</a></p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="footer-social">
                            <ul class="d-flex justify-content-md-end justify-content-center">
                                <li><a href="javascript:void(0)"><i class="lni lni-facebook-filled"></i></a></li>
                                <li><a href="javascript:void(0)"><i class="lni lni-twitter-filled"></i></a></li>
                                <li><a href="javascript:void(0)"><i class="lni lni-instagram-filled"></i></a></li>
                                <li><a href="javascript:void(0)"><i class="lni lni-linkedin-original"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
>>>>>>> 4ed8291516d5e783919b44db0b354776e73e887f
            </div>
        </section>
    </div>
    
</footer>

app/views/shared/_form.html.erb
<%= simple_form_for [@user, @review] do |review| %>
               <br>
                        <%= review.input :rating, collection: 1..5 %>
                        <%= review.input :content%>
                        <%= review.submit class: "btn btn-primary btn-sm border-radius" %>
                <% end %>

app/views/shared/_marker.html.erb
<%= image_tag "logo.png", height: 30, width: 30, alt: "Logo" %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-info navbar-lewagon">
  <div class="container-fluid">
    <%= link_to users_path, class: "navbar-brand" do %>
      <%= image_tag("uskillslogo.png", alt: "App Logo", class: "navbar-logo") %>


      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to user_messages_path(user_id: current_user.id), class: "nav-link" do %>
              <i class="fa-regular fa-envelope"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to user_path(current_user), class: "nav-link", style: "color: white; background-color:#1f2937; padding: 5px 10px; border-radius: 3px;" do %>
              Mon Profil
            <% end %>
          </li>



          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= cl_image_tag(current_user.photo.key, height: 40, width: 40, crop: :fill) if current_user.photo.attached? %>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <li class="nav-item">
                <%= link_to "Mes Reservations" , user_reservations_path(current_user), class: "dropdown-item" %>
              </li>
              <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
              </li>

            </ul>

          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_profil.html.erb
<% if current_user.role == 'teach' %>
<p>Profil Teacher</p>

  <!--====== HEADER PART START ======-->

  <header id="home" class="header-area">


        <div class="container">
            <div class="row align-items-center">
                <div class="col-xl-5 col-lg-6">
                    <div class="header-content-right">
                        <h4 class="sub-title">Hello, I’m</h4>
                        <h1 class="text-center"><%= @user.name %></h1>
                        <h3 class="card-title text-center"><%= @user.interest %></h3>
                        <!-- <a class="main-btn" href="#work">View CV</a> -->
                    </div> <!-- header content right -->
                </div>
                <div class="col-lg-6 offset-xl-1">
                    <div class="header-image d-none d-lg-block">
                        <img src="https://media.licdn.com/dms/image/D4E03AQESRl8wIrexZQ/profile-displayphoto-shrink_800_800/0/1695038981559?e=1703721600&v=beta&t=oV-OVn4l4qVrymIOsYqFsPAQiLeSLtm17Xw1zKNd_Zg" alt="hero">
                    </div> <!-- header image -->
                </div>
            </div> <!-- row -->
        </div> <!-- container -->

</header>

<!--====== HEADER PART ENDS ======-->



<!--====== ABOUT PART START ======-->

<section id="about" class="about-area pt-125 pb-130">
    <div class="container">
       <div class="cardm">
        <div class="row">
            <div class="col-lg-6">
                <div class="about-content mt-50">
                    <h1 class="text-center"><%= @user.name %></h1>
                    <p>lol
                        </p>

                </div> <!-- about content -->
            </div>
            <div class="col-xl-5 offset-xl-1 col-lg-6">
                <div class="about-skills pt-25">


                        <div class="skill-bar">
                            <div class="bar-inner">
                                <div class="bar progress-line" data-width="80">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item"><strong>skills:</strong> <%= @user.skills %></li>

                                      </ul>
                                </div>
                            </div>
                        </div>


                       
                        <div class="skill-bar">
                            <div class="bar-inner">
                                <div class="bar progress-line" data-width="60">
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item"><strong> interests:</strong> <%= @user.interest %></li>

                                      </ul>

                                </div>
                            </div>
                        </div>

                        <!-- <% if current_user.role == 'learn' %>
                          < class="cardm">
                            <%= render "shared/form" %>
                          </div>
                        <% end %>

                        <% @teacher.reviews.each do |review| %>
                         <%= review.content %>
                        <% end %> -->



                </div> <!-- about skills -->
            </div>
        </div> <!-- row -->
      </div>
    </div> <!-- container -->


</section>

<!--====== ABOUT PART ENDS ======-->







<!--====== CONTACT PART START ======-->

<section id="contact" class="contact-area pt-125 pb-130 gray-bg">
    <div class="container">
      <div class="cardm">

        <div class="row justify-content-center">
            <!-- contact box start adress mail -->
            <div class="col-lg-4 col-md-6 col-sm-7">
                <div class="contact-box text-center mt-30">
                    <div class="contact-icon">
                        <i class="lni-map-marker"></i>
                    </div>
                    <div class="contact-content">
                        <!-- <h6 class="contact-title">Address</h6> -->
                        <li class="list-group-item"><strong>Address:</strong> <%= @user.address %></li>
                    </div>
                </div> 
            </div>
            <!--  end contact box adrr mail -->
            
<!-- contact box start phone -->
            <div class="col-lg-4 col-md-6 col-sm-7">
                <div class="contact-box text-center mt-30">
                    <div class="contact-icon">
                        <i class="lni-phone"></i>
                    </div>
                    <div class="contact-content">
                        <h6 class="contact-title">Phone</h6>
                        <p>+931 2222 5555</p>

                    </div>
                </div> 
            </div>

        </div> <!-- row -->
        <!-- bloc message box start here -->
        <div class="row">
            <div class="col-lg-6">
                <div class="contact-form pt-30">
                    <form id="contact-form" action="assets/contact.php">
                        <div class="single-form">
                            <input type="text" name="name" placeholder="Name">
                        </div> <!-- single form -->
                        <div class="single-form">
                            <input type="email" name="email" placeholder="Email">
                        </div> <!-- single form -->
                        <div class="single-form">
                            <textarea name="message" placeholder="Message"></textarea>
                        </div> <!-- single form -->
                        <p class="form-message"></p>
                        <div class="single-form">
                            <button class="main-btn" type="submit">Send Message</button>
                        </div> <!-- single form -->
                    </form>
                </div> <!-- contact form -->
            </div>
            <div class="col-lg-6">
                <div class="contact-map mt-60">
                    <div class="gmap_canvas">
                        <iframe id="gmap_canvas" src="https://maps.google.com/maps?q=Mission%20District%2C%20San%20Francisco%2C%20CA%2C%20USA&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                    </div>
                </div> <!-- contact map -->
            </div>
        </div> <!-- row -->
        <!-- bloc message box Ends here -->
      </div>
    </div> <!-- container -->

<!--====== BACK TOP TOP PART START ======-->

<!-- <%= link_to "Back To Top" , users_path %> -->

<!--====== BACK TOP TOP PART ENDS ======-->
</section>

<!--====== CONTACT PART ENDS ======-->




<%end%>

app/views/shared/_profilheader.html.erb
   <!-- HEADER PART -->
   <header id="home" class="header-area">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-xl-5 col-lg-6">
          <div class="header-content-right">
            <h4 class="sub-title">Hello, I’m</h4>
            <h1 class="text-center">
              <%= @user.name %>
            </h1>
            <h3 class="card-title text-center">
              <%= @user.interest %>
            </h3>
          </div> <!-- header content right -->
        </div>
        <div class="col-lg-6 offset-xl-1">
          <div class="user-photo">
            <!-- Utilisation d'une classe différente pour la div entourant la photo -->
            <img
              src="https://media.licdn.com/dms/image/D4E03AQESRl8wIrexZQ/profile-displayphoto-shrink_800_800/0/1695038981559?e=1703721600&v=beta&t=oV-OVn4l4qVrymIOsYqFsPAQiLeSLtm17Xw1zKNd_Zg"
              alt="hero" class="img-fluid rounded-circle">
          </div> <!-- user photo -->
        </div>
      </div> <!-- row -->
    </div> <!-- container -->
  </header>
  <!-- HEADER PART ENDS -->

app/views/shared/_search.html.erb
<div class="container mt-3">
    <div class="row">
      <div class="col-12"><br>
        <h5>Quelle nouvelle compéténce voulez-vous apprendre ?</h5>
      </div>
    </div>
  
    <div class="row">
      <div class="col">
        <% if @query %>
          <p>You searched for <strong><%= @query %></strong>. We found <%= @skills.count %> Skills out of our <%= Skill.count %> on our website.</p>
        <% else %>
          <p>All <%= Skill.count %> skills.</p>
        <% end %>
  
  
      </div>
    </div><br>
  </div>

app/views/shared/_section.html.erb
<section id="home" class="hero-area">
  <div class="banner">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-8 offset-lg-2 text-center">
          <h3 class="hero-title">Apprenez à Votre Rythme, Enrichissez Votre Avenir</h3>
          <p class="hero-subtitle">Découvrez des Cours Uniques Dispensés par des Experts</p>
                <%= form_tag(search_skills_path, method: :get, class: "d-flex") do %>
                          <input class="form-control me-2" name="query" type="search" placeholder="Recherchez une catégorie" aria-label="Search" value="<%= params[:query] %>">

                          <button class="btn btn-search" type="submit">Rechercher</button>
                          <% end %>

        </div>
      </div>
    </div>
  </div>
</section>