config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :skills do
    collection do
      get :search
    end
    resources :skills, only: [:create, :show, :edit, :update, :destroy]
  end

  resources :users do
    resources :reviews, only: [:create, :show, :edit, :update, :destroy]
    resources :reservations
    resources :messages, only: [:index,:show, :new, :create, :destroy]
  end

  post 'validate', to: 'reservations#validate'

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :teacher, :class_name => 'User'
  belongs_to :student, :class_name => 'User'
  
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :find_reservation, only: [:show, :destroy, :edit, :update]

  def index
    # @reservations = Reservation.all
    if current_user.role == "teach"
    @reservations = Reservation.where(teacher_id: current_user)
    else
      @reservations = Reservation.where(student_id: current_user)
    end
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @user = User.find(params[:user_id].to_i)
    @reservation = Reservation.new(reservation_params)

    @reservation.student_id = current_user.id
    @reservation.teacher_id = @user.id

    if @reservation.save
      redirect_to user_reservations_path(@user), notice: 'La réservation a été créée avec succès.'
    else
      flash.now[:alert] = 'Erreur lors de la création de la réservation.'
      render :new, status: :unprocessable_entity
    end
  end

  def show
    # Avant cette action, la réservation est déjà chargée par le filtre before_action.
  end

  def destroy
    @reservation.update(statut: 'Refusée')
    redirect_to user_reservations_path(current_user), notice: 'La réservation a été refusée.'
  end

  def edit
    # L'action d'édition devrait simplement rendre le formulaire existant.
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to user_reservations_path(@reservation.teacher), notice: 'La réservation a été mise à jour avec succès.'
    else
      flash.now[:alert] = 'Erreur lors de la mise à jour de la réservation.'
      render :edit, status: :unprocessable_entity
    end
  end

  def validate
    @reservation = Reservation.find(params[:reservation_id].to_i)
    @reservation.update(statut: "Validée")
    redirect_to user_reservations_path(current_user)
  end

  private

  def find_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:student_id, :teacher_id, :start_date, :end_date)
  end
end

app/views/reservations/edit.html.erb
<%= simple_form_for @reservation, url: user_reservation_path(@reservation.teacher, @reservation), method: :patch do |f| %>
  <div class="container mt-4">
    <h1 class="text-center">Update Your Reservation</h1>

    <div class="card mt-4">
      <div class="card-body">
        <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker" } } %>
        <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker" } } %>

        <div class="text-center mt-3">
          <%= f.button :submit, "Update", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/reservations/index.html.erb
<div class="container mt-4">
  <div class="header">
    <h2 class="greeting mb-4">👋 Bonjour <%= current_user.name %>, voici tes réservations :</h2>
  </div>

  <% @reservations.each do |reservation| %>
    <div class="card-formateur mb-4">
      <div class="card-formateur-header">
        <div class="card-formateur-image">
        <% if current_user.role == 'learn' %>
          <%= cl_image_tag(reservation.teacher.photo.key, height: 100, width: 100, crop: :fill) if reservation.teacher.photo.attached? %>
        <% else %>
          <%= cl_image_tag(reservation.student.photo.key, height: 100, width: 100, crop: :fill) if reservation.student.photo.attached? %>
        <% end %>
        </div>
        <% if current_user.role == 'learn' %>
        <div class="card-formateur-info">
          <p class="card-formateur-name"><%= reservation.teacher.name %> <%= reservation.teacher.last_name %></p>
          <p class="card-formateur-interest"><i class="fas fa-book"></i> <%= reservation.teacher.interest %></p>
        </div>
        <% else %>
          <div class="card-formateur-info">
          <p class="card-formateur-name"><%= reservation.student.name %> <%= reservation.student.last_name %></p>
          <p class="card-formateur-interest"><i class="fas fa-book"></i> <%= reservation.student.interest %></p>
        </div>
        <% end %>
      </div>
      <div class="card-formateur-body">
        <div class="card-formateur-stats mx-2">
          <p class="card-formateur-avis">
            Avis
            <span class="state-value"><%= render_rating(reservation.teacher.rating) %></span>
          </p>
        </div>
        <div class="card-formateur-details ">
          <div class="card-formateur-date mx-2">
            <p>Début : <%= reservation.start_date.strftime('%d %b %Y') %></p>
            <p>Fin : <%= reservation.end_date.strftime('%d %b %Y') %></p>
          </div>
          <div class="card-formateur-actions">
            <% if current_user.role == 'teach' %>
            <% if reservation.statut == "En attente"  %>
            <%= button_to "Accepter", validate_path(), method: :post, params: { reservation_id: reservation.id }, class: "btn btn-primary mb-2" %>

            <%= link_to "Refuser", user_reservation_path(reservation.teacher, reservation), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr(e)?" }, class: "btn btn-danger" %>
            <% end %>
            <% else %>
              <!-- Handle other cases as needed -->
            <% end %>
            <%= reservation.statut %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reservations/show.html.erb
<div class="mt-4" data-controller="sweetalert">
  <div class="container show-reservation ">
    <% if @reservation.statut == 'Validée' %>
      <div class="reservation-card card border border-black mb-3 bg-success">
    <% elsif @reservation.statut == 'Refusée'%>
      <div class="reservation-card card border border-black mb-3 bg-danger">
    <% else %>
      <div class="reservation-card card border border-black mb-3">
    <% end %>
      <div class="card-header bg-transparent border-black">
        <h1>Détails de votre Réservation</h1>
      </div>
        <div class="card-body text-black">
          <p><%= @reservation.student.name %> <%= @reservation.student.last_name %> te propose une demande déchanges de compétences</p>
          <p>du: <%= @reservation.start_date %></p>
          <p>au: <%= @reservation.end_date %></p>
        </div>
      <div class="card-footer bg-transparent border-black">
        Merci pour votre réservation.
      </div>
    </div>

    <div class="d-grid gap-2 col-6 mx-auto">
      <%= link_to 'Back to Home', user_reservations_path(@reservation.teacher), class: "btn btn-primary" %>
    </div>
  </div>

</div>